openapi: 3.0.0
info:
  title: "LudoAPI"
  description: "This is a Ludo game API"
  contact:
    name: API Support
    email: olssonolof@hotmail.com
  version: "1.0.0"
paths:
  api/ludo/game/games:
    get:
      description: Get list of games.
      summary: Get a list of all games.
      operationID: LudoEngine
      responses:
        '200':
          description: List of games
          content:
            application/json:
              schema:
                type: object
                properties:
                  game:
                    type: string
                    description: The name of the game.
                example: 
                    {
                      game: exampleGame
                    }
        '404':
          description: Couldn't get list.
  api/ludo/game/creategame:
    post:
      description: Create new game.
      summary: Creates a new game.
      parameters:
        - in: body
          name: game
          description: The game to create.
          schema:
            type: string[]
            required:
              - numberOfPlayers
              - gameName
              - 1
            properties:
              numberOfPlayers:
                type: string
              gameName:
                type: string
              1:
                type: string
      responses:
        '200':
          description: Game was created.
          content:
            application/json:
              schema:
                type: object
                properties:
                  player:
                    type: string
                    description: The color of next player.
                  diceThrow:
                    type: integer
                    description: The value of the dice throw.
                example: 
                  {
                    player: blue,
                    diceThrow: 4
                  }
        '404':
          description: Couldn't create game
  api/ludo/game/loadgame/{gamename}:
    post:
      description: Load saved game.
      summary: Loads the saved game.
      responses:
        '200':
          description: Game was loaded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  player:
                    type: string
                    description: The color of next player.
                  diceThrow:
                    type: integer
                    description: The value of the dice throw.
                example: 
                  {
                    player: blue,
                    diceThrow: 4
                  }
        '404':
          description: Couldn't create game
  api/ludo/game/gameinfo:
    get:
      description: Get game information.
      summary: Get game information.
      responses:
        '200':
          description: Game information recieved.
          content:
            application/json:
              schema:
                type: object
                properties:
                  gameInfo: 
                    type: string
                    description: Return information about the game state.
                example:
                  {
                    Blue 1 is in nest.,
                    Blue 2 is in nest.,
                    Blue 3 is in nest.,
                    Blue 4 is in nest.
                  }
        '404':
          description: Couldn't recieve information
  api/ludo/game/updatedpieceposition/{pieceNumber}:
    put:
      description: Update piece position
      summary: Update piece position
      responses:
        '200':
          description: Piece position updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  player: 
                    type: string
                    description: Return string from method.
                  movePiece:
                    type: string
                    description: Information about movement action.
                example:
                  {
                    player: Blue,
                    movePiece: That piece can't move. Next player.
                  }
        '404':
          description: Couldn't update position
  api/ludo/game/savegame:
    post:
      description: Saves the current game
      summary: Saves the current game
      responses:
        '200':
          description: Game was saved
          content:
            application/json:
              schema:
                type: object
                properties:
                  game:
                    type: string
                    description: Information if game was saved
                example:
                  {
                    game: GameName was saved
                  }
        '404':
          description: Game wasent saved
