openapi: 3.0.0
info:
  title: "LudoAPI"
  description: "This is a Ludo game API"
  contact:
    name: API Support
    email: olssonolof@hotmail.com
  version: "1.0.0"
paths:
  /ludo/game:
    get:
      tag:
       - game
      description: Get list of games
      summary: Get a list of all games
      operationID: LudoEngine
      responses:
        '200':
          description: List of games
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: The user ID.
                  username:
                    type: string
                    description: The user name.
                example: 
                  id: 1
                  username: game1
        '404':
          description: Couldn't get list
    post:
      description: Create new game
      summary: Creates a new game
      responses:
        '200':
          description: Game was created
        '404':
          description: Couldn't create game
    delete:
      description: Remove game
      summary: Remove game
      responses:
        '200':
          description: Game removed
        '404':
          description: Couldn't remove game
  /ludo/whosTurn/diceThrow/positionOfPieces:
    get:
      description: Get player information
      summary: Get player information
      responses:
        '200':
          description: Player information recieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  color:
                    type: string
                    description: Who's turn by colour
                  diceThrow:
                    type: integer
                    description: Value of dice throw
                  positionOfPieces:
                    type: object
                    properties:
                      piece1: 
                        type: object
                        description: Piece one object
                      piece2:
                        type: object
                        description: Piece two object
                      piece3:
                        type: object
                        description: Piece three object
                      piece4:
                        type: object
                        description: Piece four object
                    description: Position of every piece
                example:
                  color: blue
                  diceThrow: 6
                  positionOfPieces: 
                    {
                      piece1: {},
                      piece2: {},
                      piece3: {},
                      piece4: {}
                    }
        '404':
          description: Couldn't recieve information
    put:
      description: Update piece position
      summary: Update piece position
      responses:
        '200':
          description: Piece position updated
        '404':
          description: Couldn't update position
